language: java
jdk: oraclejdk6
env:
    matrix:
    - ANDROID_SDKS=sysimg-16            ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-17,sysimg-17 ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
before_install:
    # Install base Android SDK
    #- sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22-linux.tgz
    - tar xzf android-sdk_r22-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # Install required Android components.
    - android list sdk
    - android update sdk --filter platform-tools,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force

    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - ./wait_for_emulator

script: mvn install -Pintegration-tests -Dandroid.device=test
